# Imagem base
FROM python:3.10

# Diretório dentro do container
WORKDIR /app

# Copia os arquivos
COPY . .

# Instala dependências
RUN pip install -r requirements.txt

# Expõe a porta
EXPOSE 5000

# Comando para rodar o app
CMD ["python", "app.py"]